version: 0.5

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 463748998377.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...
      - docker build -t coworking-checkin:0.0.1 .
      - docker tag coworking-checkin:0.0.1 463748998377.dkr.ecr.us-east-1.amazonaws.com/coworking-checkin:0.0.1
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 463748998377.dkr.ecr.us-east-1.amazonaws.com/coworking-checkin:0.0.1
